# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window2.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class HomeUI(object):
    def setupUi(self, HomeWindow):
        HomeWindow.setObjectName("HomeWindow")
        HomeWindow.resize(484, 304)
        self.centralwidget = QtWidgets.QWidget(HomeWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(90, 20, 301, 41))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(130, 70, 211, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(340, 160, 60, 16))
        self.label_3.setObjectName("label_3")
        self.order_number = QtWidgets.QLabel(self.centralwidget)
        self.order_number.setGeometry(QtCore.QRect(340, 230, 131, 20))
        self.order_number.setObjectName("order_number")
        self.lcdNumber = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber.setGeometry(QtCore.QRect(170, 140, 151, 131))
        self.lcdNumber.setDigitCount(5)
        self.lcdNumber.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber.setProperty("value", 0.0)
        self.lcdNumber.setProperty("intValue", 0)
        self.lcdNumber.setObjectName("lcdNumber")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(20, 140, 131, 121))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("gambar.jpg"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        HomeWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(HomeWindow)
        QtCore.QMetaObject.connectSlotsByName(HomeWindow)

    def retranslateUi(self, HomeWindow):
        _translate = QtCore.QCoreApplication.translate
        HomeWindow.setWindowTitle(_translate("HomeWindow", "Home"))
        self.label.setText(_translate("HomeWindow", "SISTEM TIKET PARKIR BERTINGKAT"))
        self.label_2.setText(_translate("HomeWindow", "SELAMAT DATANG DI LAYANAN PARKIR KAMI"))
        self.label_3.setText(_translate("HomeWindow", "GATE 01"))
        self.order_number.setText(_translate("HomeWindow", "No Urut"))



class PayUI(object):
    def setupUi(self, PayWindow):
        PayWindow.setObjectName("PayWindow")
        PayWindow.resize(481, 304)
        font = QtGui.QFont()
        font.setPointSize(15)
        PayWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(PayWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(90, 20, 301, 41))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 110, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.lblbarcode = QtWidgets.QLabel(self.centralwidget)
        self.lblbarcode.setGeometry(QtCore.QRect(110, 110, 201, 16))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lblbarcode.setFont(font)
        self.lblbarcode.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblbarcode.setObjectName("lblbarcode")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 132, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(10, 154, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(10, 176, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.lblHarga = QtWidgets.QLabel(self.centralwidget)
        self.lblHarga.setGeometry(QtCore.QRect(30, 210, 431, 71))
        font = QtGui.QFont()
        font.setPointSize(47)
        font.setBold(True)
        font.setWeight(75)
        self.lblHarga.setFont(font)
        self.lblHarga.setObjectName("lblHarga")
        self.lblmasuk = QtWidgets.QLabel(self.centralwidget)
        self.lblmasuk.setGeometry(QtCore.QRect(110, 132, 201, 16))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lblmasuk.setFont(font)
        self.lblmasuk.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblmasuk.setObjectName("lblmasuk")
        self.lblkeluar = QtWidgets.QLabel(self.centralwidget)
        self.lblkeluar.setGeometry(QtCore.QRect(110, 154, 201, 16))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lblkeluar.setFont(font)
        self.lblkeluar.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblkeluar.setObjectName("lblkeluar")
        self.lbldurasi = QtWidgets.QLabel(self.centralwidget)
        self.lbldurasi.setGeometry(QtCore.QRect(110, 176, 201, 16))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lbldurasi.setFont(font)
        self.lbldurasi.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lbldurasi.setObjectName("lbldurasi")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(330, 120, 111, 61))
        self.pushButton.setObjectName("pushButton")
        PayWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(PayWindow)
        QtCore.QMetaObject.connectSlotsByName(PayWindow)

    def retranslateUi(self, PayWindow):
        _translate = QtCore.QCoreApplication.translate
        PayWindow.setWindowTitle(_translate("PayWindow", "Payment"))
        self.label.setText(_translate("PayWindow", "SISTEM TIKET PARKIR BERTINGKAT"))
        self.label_2.setText(_translate("PayWindow", "Scan Tiket"))
        self.lblbarcode.setText(_translate("PayWindow", "5924852802859302"))
        self.label_4.setText(_translate("PayWindow", "Jam Masuk"))
        self.label_5.setText(_translate("PayWindow", "Jam Keluar"))
        self.label_6.setText(_translate("PayWindow", "Durasi Parkir"))
        self.lblHarga.setText(_translate("PayWindow", "<html><head/><body><p><span style=\" color:#fc0107;\">Rp1.000.000,00</span></p></body></html>"))
        self.lblmasuk.setText(_translate("PayWindow", "10:20:30"))
        self.lblkeluar.setText(_translate("PayWindow", "10:20:30"))
        self.lbldurasi.setText(_translate("PayWindow", "10 Menit"))
        self.pushButton.setText(_translate("PayWindow", "SELESAI"))

